apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to manage Helm release secrets
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - "*"
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for app.letout.io/v1alpha1, Kind: Laravel
##
- apiGroups:
  - app.letout.io
  resources:
  - laravels
  - laravels/status
  - laravels/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"

#+kubebuilder:scaffold:rules
