apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laravel.fullname" . }}-letout-actions
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
data:
  git-action: |-
    #!/bin/bash -e
    set -xe
    
    rm -rf /var/www/html/* 2>/dev/null || true
    rm -rf /var/www/html/.* 2>/dev/null || true

    /usr/bin/git clone {{ .Values.git.repo }} /var/www/html
    /usr/local/bin/composer install --working-dir /var/www/html
    /bin/chown -R www-data:www-data /var/www/html

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laravel.fullname" . }}-laravel-actions
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
data:
  post-start: |-
    {{ .Values.postStart | nindent 4 }}
  pre-stop: |-
    {{ .Values.preStop | nindent 4 }}
  pre-stop-worker: |-
    {{ .Values.preStopWorker | nindent 4 }}
  stop-worker: |-
    {{ .Values.stopWorker | nindent 4 }}
  start-worker: |-
    {{ .Values.startWorker | nindent 4 }}
